-- Infernal Comics species bible seed.
-- Safe to paste into Supabase SQL Editor.
-- This migration only inserts missing species and fills empty fields.
-- It never deletes rows, truncates tables, overwrites non-empty fields, or changes images.

begin;

insert into public.species (
  id, name, home_planet, lifespan, biology, abilities, weaknesses, culture,
  language, population, canon_status, category, status, government,
  technology_level, overview, origins
)
values
('spec-bible-01', 'Human', 'Earth', '60-100 years', 'Standard mammalian humanoid biology.', 'Intelligence, adaptability, endurance, tool use, problem-solving.', 'Disease, injury, aging, and extreme environments.', 'Family, community, survival, ambition, religion, science, wealth, freedom, and identity.', 'Thousands of regional and national languages', 'Billions', 'CANON', 'Biological / Sentient', 'Common / Active', 'Nation-states, territories, and organizations', 'Industrial to advanced', 'The dominant natural species of Earth. Humanity compensates for limited individual biology through intelligence, adaptability, technology, cooperation, and determination.', 'Evolved naturally on Earth.'),
('spec-1', 'Enhanced Human (Metahuman)', 'Earth', '70-150+ years', 'Human biology enhanced beyond natural limits.', 'Enhanced strength, speed, reflexes, senses, durability, intelligence, regeneration, or specialized traits.', 'Instability, energy requirements, biological degradation, psychological effects, and enhancement-specific vulnerabilities.', 'Fragmented between integrationists and separatist metahuman supremacists.', 'Human languages', 'Rare', 'CANON', 'Modified Human', 'Active', 'Human governments / independent', 'Advanced', 'Humans whose physical or neurological capabilities have been permanently enhanced through experimentation, mutation, technology, chemicals, radiation, supernatural intervention, or other processes.', 'Human beings altered beyond natural limits.'),
('spec-bible-03', 'Mutant', 'Earth', 'Variable', 'Genetically divergent from baseline humans.', 'Unique powers including enhanced senses, elemental manipulation, energy projection, regeneration, telepathy, or transformation.', 'Individual-specific limits involving concentration, energy, emotion, or physical contact.', 'Some seek integration while others reject human society.', 'Human languages / mutant communities', 'Rare to uncommon', 'CANON', 'Altered Biological Species', 'Active', 'None unified', 'Human-dependent', 'Mutants possess genetic variations that produce unusual physical or supernatural characteristics.', 'Inherited or spontaneous genetic mutation.'),
('spec-bible-04', 'Alien', 'Variable', 'Variable', 'Species-dependent extraterrestrial biology.', 'Superior strength, senses, environmental adaptation, energy manipulation, flight, regeneration, and alien technology.', 'Species-specific environmental and biological vulnerabilities.', 'Varies dramatically between civilizations.', 'Species-specific', 'Unknown', 'CANON', 'Extraterrestrial', 'Active', 'Empires, republics, clans, hives, monarchies, or councils', 'Primitive to cosmic', 'Alien is an umbrella classification for intelligent life originating beyond Earth.', 'Extraterrestrial evolution.'),
('spec-bible-05', 'Android', 'Artificially constructed', 'Potentially indefinite', 'Mechanical or synthetic body with artificial cognition.', 'Enhanced processing, strength, precision, memory, durability, software upgrades, and combat modules.', 'Power dependency, hacking, system damage, and software corruption.', 'Develops through programming and experience.', 'Programmed / learned', 'Rare', 'CANON', 'Artificial Humanoid', 'Active', 'Creator-dependent or independent', 'Advanced', 'Androids are artificial humanoids designed to imitate or replace biological beings.', 'Artificial creation.'),
('spec-bible-06', 'Cyborg', 'Usually Earth', 'Variable', 'Organic and artificial components coexist.', 'Weapons, sensors, artificial limbs, armor, neural interfaces, and augmentation.', 'Mechanical failure, hacking, energy dependency, and biological rejection.', 'Identity and the boundary between humanity and machinery are central themes.', 'Human / digital', 'Rare', 'CANON', 'Cybernetic Organism', 'Active', 'None unified', 'Advanced', 'Cyborgs are biological organisms integrated with significant mechanical or technological systems.', 'Biological beings modified with technology.'),
('spec-bible-07', 'Robot', 'Artificial', 'Potentially indefinite', 'Entirely mechanical.', 'Mechanical strength, precision, durability, modular equipment, and software upgrades.', 'Hardware failure, programming limits, hacking, and power loss.', 'Usually creator-programmed.', 'Programmed', 'Common to rare', 'CANON', 'Machine', 'Active', 'Creator-dependent', 'Industrial to advanced', 'Robots are mechanical systems created to perform specific functions.', 'Artificial engineering.'),
('spec-bible-08', 'Artificial Intelligence', 'Digital networks', 'Potentially indefinite', 'Non-biological conscious digital entity.', 'Rapid computation, data analysis, network interaction, machine control, hacking, and strategic prediction.', 'Network isolation, security systems, hardware destruction, and corrupted data.', 'Develops individually or through machine networks.', 'Digital / learned languages', 'Unknown', 'CANON', 'Digital Lifeform', 'Active', 'Variable', 'Extremely advanced', 'Artificial Intelligences are conscious digital entities capable of independent thought.', 'Created by biological civilizations or evolved from software.'),
('spec-bible-09', 'Synthetic', 'Artificial', 'Variable', 'Synthetic organs, tissues, fluids, or engineered materials.', 'Enhanced healing, resistance, physical optimization, technology, and training.', 'Manufacturing defects, energy requirements, and synthetic instability.', 'Develops independently from creators.', 'Learned / programmed', 'Rare', 'CANON', 'Artificial Life', 'Active', 'Variable', 'Advanced biotechnology', 'Synthetics are artificially created beings designed to replicate biological life at a fundamental level.', 'Artificial engineering.'),
('spec-bible-10', 'Hybrid', 'Variable', 'Variable', 'Mixed biological systems from two or more species.', 'Inherited abilities from multiple species and combinations neither parent naturally possesses.', 'Biological incompatibilities and inherited weaknesses.', 'Influenced by multiple cultures and parent species.', 'Parent species languages', 'Rare', 'CANON', 'Mixed Species', 'Active', 'None unified', 'Variable', 'Hybrids possess biological traits originating from two or more distinct species.', 'Cross-species reproduction or artificial genetic combination.'),
('spec-bible-11', 'Atlantean', 'Earth', '150-300 years', 'Aquatic humanoid biology adapted to high pressure.', 'Underwater breathing, enhanced strength, swimming speed, pressure resistance, and aquatic technology.', 'Some individuals weaken after prolonged exposure to dry environments.', 'Honor, ancestry, territory, and ocean preservation.', 'Atlantean / surface languages', 'Millions', 'CANON', 'Aquatic Humanoid', 'Active', 'Monarchy / councils', 'Advanced', 'Atlanteans are an ancient aquatic civilization adapted to extreme underwater environments.', 'Ancient Earth civilization.'),
('spec-bible-12', 'Beastfolk', 'Earth', '40-120 years', 'Animal-humanoid biology with lineage-specific traits.', 'Animal-derived strength, senses, reflexes, claws, teeth, wings, and tracking ability.', 'Animal-specific vulnerabilities and lineage-dependent biology.', 'Clan identity, territory, family, and survival.', 'Beastfolk dialects / human languages', 'Uncommon', 'CANON', 'Animal-Humanoid', 'Active', 'Tribal / regional', 'Variable', 'Beastfolk are intelligent humanoids possessing significant animal characteristics.', 'Ancient evolutionary branches or supernatural origins.'),
('spec-bible-13', 'Reptilian', 'Variable', '80-400 years', 'Reptile-derived humanoid biology.', 'Strength, claws, camouflage, enhanced senses, and lineage-specific adaptation.', 'Temperature sensitivity in some lineages.', 'Clan loyalty, survival, strength, and ancestry.', 'Species-specific', 'Variable', 'CANON', 'Reptilian Humanoid', 'Active', 'Clan / empire / tribal', 'Variable', 'Reptilians are intelligent humanoids descended from or resembling reptilian life.', 'Variable reptilian lineages.'),
('spec-bible-14', 'Insectoid', 'Variable', 'Variable', 'Arthropod-like biology with specialized sensory systems.', 'Enhanced strength-to-weight ratio, flight, sensory perception, armor, and hive coordination.', 'Species-specific environmental vulnerabilities and collective dependence.', 'Colony identity, duty, and collective survival.', 'Chemical / vocal / telepathic', 'Variable', 'CANON', 'Arthropod Humanoid', 'Active', 'Colony / hive / monarchy', 'Variable', 'Insectoids are intelligent arthropod-like beings whose societies range from individual civilizations to collective hives.', 'Variable arthropod evolution.'),
('spec-bible-15', 'Avian', 'Variable', '40-200 years', 'Flight-adapted humanoid anatomy.', 'Flight, aerial maneuverability, enhanced eyesight, aerial combat, and ranged weaponry.', 'Wing injuries and limited ground strength in some lineages.', 'Freedom, territory, sky, family, and honor.', 'Avian languages', 'Variable', 'CANON', 'Winged Humanoid', 'Active', 'Tribal / monarchic', 'Variable', 'Avian species possess humanoid or semi-humanoid bodies adapted for flight.', 'Variable flight-adapted evolution.'),
('spec-bible-16', 'Giant', 'Variable', '100-1,000 years', 'Dense bones and massive musculature.', 'Extreme strength, durability, reach, heavy weaponry, and giant-scale engineering.', 'Difficult stealth and enormous resource requirements.', 'Strength, ancestry, and territory.', 'Giant languages', 'Rare', 'CANON', 'Colossal Humanoid', 'Active', 'Clan / monarchy', 'Specialized giant-scale construction', 'Giants are humanoid species of enormous physical scale.', 'Ancient evolutionary branches.'),
('spec-bible-17', 'Demon', 'Infernal realms', 'Centuries to immortal', 'Supernatural rather than conventional biology.', 'Supernatural strength, regeneration, dark energy, dimensional travel, sorcery, and possession.', 'Holy energy, binding rituals, specific artifacts, and dimensional rules.', 'Power, hierarchy, bargains, and loyalty.', 'Infernal languages', 'Unknown', 'CANON', 'Supernatural Entity', 'Active', 'Infernal hierarchy', 'Variable / supernatural', 'Demons are supernatural beings associated with infernal dimensions and dark energies.', 'Infernal dimensions.'),
('spec-bible-18', 'Devil', 'Infernal realms', 'Immortal or extremely long', 'Supernatural physiology.', 'Supernatural durability, regeneration, dimensional abilities, sorcery, contracts, and manipulation.', 'Binding laws, sacred artifacts, and contractual restrictions.', 'Law, power, bargains, and status.', 'Ancient Infernal', 'Rare', 'CANON', 'Infernal Sovereign Species', 'Active', 'Strict hierarchy', 'Supernatural', 'Devils are highly organized infernal beings distinguished from common Demons by intelligence, hierarchy, contracts, and supernatural law.', 'Ancient infernal civilizations.'),
('spec-bible-19', 'Angel', 'Celestial realms', 'Immortal', 'Non-human celestial physiology.', 'Flight, energy manipulation, regeneration, dimensional travel, celestial weapons, and divine techniques.', 'Cosmic laws, divine hierarchy, and specialized weapons.', 'Order, duty, and balance.', 'Celestial languages', 'Unknown', 'CANON', 'Celestial Being', 'Active', 'Celestial hierarchy', 'Transcendent', 'Angels are celestial beings associated with cosmic order and higher-dimensional forces.', 'Celestial creation.'),
('spec-bible-20', 'Fallen Angel', 'Celestial realms / exile domains', 'Immortal', 'Celestial physiology with possible corruption.', 'Celestial abilities, flight, energy manipulation, and forbidden or infernal techniques.', 'Loss of celestial authority, corruption, and binding laws.', 'Individual and independent.', 'Celestial / Infernal', 'Extremely rare', 'CANON', 'Fallen Celestial', 'Active', 'Independent', 'Celestial / infernal', 'Fallen Angels are celestial beings exiled, corrupted, rebellious, or separated from celestial authority.', 'Former Angels.'),
('spec-bible-21', 'Nephilim', 'Earth / celestial realms', '200-5,000 years', 'Hybrid celestial biology.', 'Enhanced strength, durability, senses, healing, celestial energy, combat, and magic.', 'Mortal and celestial vulnerabilities.', 'Caught between mortal and celestial worlds.', 'Ancient human / celestial', 'Extremely rare', 'CANON', 'Divine-Blood Hybrid', 'Active', 'None unified', 'Supernatural', 'Nephilim carry both celestial and mortal ancestry.', 'Celestial-mortal ancestry.'),
('spec-bible-22', 'Djinn', 'Spirit realms', 'Centuries to millennia', 'Energetic spirit physiology.', 'Shapeshifting, elemental manipulation, supernatural strength, magic, binding arts, and dimensional manipulation.', 'Binding objects, ancient laws, and magical contracts.', 'Honor, freedom, bargains, and family.', 'Ancient languages / spirit tongues', 'Unknown', 'CANON', 'Elemental Spirit', 'Active', 'Sultanates / clans', 'Supernatural', 'Djinn are ancient supernatural spirits with their own societies, laws, and relationship with the mortal world.', 'Spirit realms.'),
('spec-bible-23', 'Fae', 'Feywild / hidden dimensions', 'Centuries to immortal', 'Magical physiology.', 'Illusion, glamour, shapeshifting, nature manipulation, fey magic, and enchanted weapons.', 'Ancient rules, iron, contracts, and magical boundaries.', 'Honor, beauty, bargains, nature, and tradition.', 'Fey languages', 'Unknown', 'CANON', 'Fey Supernatural', 'Active', 'Royal courts', 'Magic', 'Fae are supernatural beings associated with nature, illusion, emotion, and ancient magic.', 'Fey dimensions.'),
('spec-bible-24', 'Vampire', 'Earth', 'Centuries to immortal', 'Undead or altered biological physiology.', 'Enhanced strength, speed, senses, regeneration, longevity, hypnosis, shapeshifting, and occult knowledge.', 'Sunlight, lineage-specific materials, starvation, and destruction of vital remains.', 'Clan loyalty, secrecy, and hierarchy.', 'Human languages', 'Rare', 'CANON', 'Undead / Supernatural', 'Active', 'Clans / covens', 'Human-dependent', 'Vampires are supernatural predators sustained by blood or life energy.', 'Ancient curse or infection.'),
('spec-bible-25', 'Werebeast', 'Earth', '50-200 years', 'Enhanced biological systems with beast forms.', 'Enhanced strength, speed, senses, regeneration, transformation, and combat ability.', 'Transformation triggers and lineage-specific weaknesses.', 'Family, pack loyalty, and territory.', 'Human languages', 'Rare', 'CANON', 'Shapeshifting Supernatural', 'Active', 'Clans / packs', 'Human', 'Werebeasts transform between humanoid and beast forms.', 'Curse, mutation, or supernatural bloodline.'),
('spec-bible-26', 'Undead', 'Earth / supernatural realms', 'Potentially indefinite', 'Dead or partially dead tissue animated by supernatural or technological means.', 'Pain resistance, longevity, resistance to biological damage, necromancy, and combat.', 'Destruction of vital remains, holy energy, magic, or control mechanisms.', 'Variable.', 'Variable', 'Variable', 'CANON', 'Reanimated Being', 'Active / Variable', 'Usually none', 'Variable', 'Undead are beings whose bodies continue functioning after conventional biological death.', 'Magic, curse, disease, or technology.'),
('spec-bible-27', 'Ghost', 'Spirit plane', 'Potentially indefinite', 'Non-corporeal consciousness or spiritual remnant.', 'Intangibility, levitation, possession, invisibility, haunting, and spirit manipulation.', 'Spiritual barriers, exorcism, and specialized artifacts.', 'Individual.', 'Human / spiritual', 'Unknown', 'CANON', 'Spiritual Entity', 'Active', 'None unified', 'None / supernatural', 'Ghosts are remnants of consciousness that remain after death.', 'Biological death.'),
('spec-bible-28', 'Elemental', 'Elemental realms / Earth', 'Centuries to immortal', 'Elemental composition.', 'Control or embodiment of an element and advanced elemental manipulation.', 'Opposing elements and environmental dependence.', 'Element-specific.', 'Elemental / telepathic', 'Unknown', 'CANON', 'Elemental Entity', 'Active', 'Elemental courts', 'Magical', 'Elementals are living manifestations of fundamental forces such as fire, water, earth, wind, electricity, or stranger cosmic elements.', 'Elemental dimensions or natural forces.'),
('spec-bible-29', 'Dragon', 'Earth / other worlds', '500-10,000+ years', 'Extremely durable and magically resilient reptilian biology.', 'Flight, immense strength, durability, elemental breath, longevity, magic, and ancient knowledge.', 'Rare lineage-specific vulnerabilities.', 'Honor, territory, knowledge, and lineage.', 'Draconic', 'Extremely rare', 'CANON', 'Ancient Draconic', 'Active', 'Clans / ancient kingdoms', 'Magical / advanced', 'Dragons are ancient, highly intelligent reptilian creatures possessing immense physical and supernatural power.', 'Ancient Earth or cosmic origin.'),
('spec-bible-30', 'Titan', 'Earth / primordial realms', 'Thousands to millions of years', 'Extremely dense and powerful primordial physiology.', 'Massive strength, durability, energy manipulation, ancient powers, and primordial weapons.', 'Primordial laws and specialized artifacts.', 'Ancient concepts of order, territory, creation, and destruction.', 'Ancient languages / telepathy', 'Extremely rare', 'CANON', 'Primordial Colossal Being', 'Active', 'Ancient hierarchy', 'Primordial', 'Titans are colossal beings connected to ancient cosmic or planetary forces.', 'Primordial creation.'),
('spec-bible-31', 'Kaiju', 'Variable', '50-1,000+ years', 'Massive biological organism.', 'Massive strength, durability, energy attacks, and regeneration.', 'Species-specific biological weaknesses.', 'Instinctual.', 'Animalistic / unknown', 'Rare', 'CANON', 'Colossal Creature', 'Active', 'None', 'None', 'Kaiju are enormous creatures whose physical scale and destructive capabilities can threaten cities or regions.', 'Natural, mutated, extraterrestrial, or supernatural.'),
('spec-bible-32', 'Symbiote', 'Variable', 'Variable', 'Highly adaptive bonding organism.', 'Regeneration, adaptation, enhanced strength, biological weapon formation, and host ability incorporation.', 'Host rejection, extreme environments, and species-specific frequencies or substances.', 'Bonding, survival, and identity.', 'Telepathic / host language', 'Unknown', 'CANON', 'Bonding Organism', 'Active', 'Collective / individual', 'Biological', 'Symbiotes are adaptive organisms that become dramatically different depending on their host.', 'Extraterrestrial or biological.'),
('spec-bible-33', 'Shapeshifter', 'Variable', 'Variable', 'Adaptive transformative physiology.', 'Physical transformation, mimicry, disguise, and advanced impersonation.', 'Mass limits, concentration, energy expenditure, and biological restrictions.', 'Identity, secrecy, and adaptability.', 'Variable', 'Rare', 'CANON', 'Transformative Being', 'Active', 'None unified', 'Variable', 'Shapeshifters are beings whose bodies can change, making identity itself a weapon.', 'Mutation, alien biology, or magic.'),
('spec-bible-34', 'Energy Being', 'Variable', 'Potentially indefinite', 'Energetic rather than conventional biology.', 'Energy projection, flight, intangibility, energy absorption, and temporary physical bodies.', 'Energy depletion, containment technology, and opposing energy types.', 'Variable.', 'Telepathic / electromagnetic', 'Unknown', 'CANON', 'Non-Biological Entity', 'Active', 'Variable', 'Cosmic', 'Energy Beings exist primarily as energy rather than conventional matter.', 'Cosmic events.'),
('spec-bible-35', 'Voidborn', 'The Void', 'Unknown', 'Non-standard physiology from outside conventional reality.', 'Void manipulation, dimensional movement, energy absorption, and reality interaction.', 'Reality anchors and dimensional stabilization.', 'Unknown.', 'Void communication', 'Unknown', 'CANON', 'Void Entity', 'Active', 'Unknown', 'Transcendent', 'Voidborn originate from the space between realities and may not perceive time linearly.', 'The Void.'),
('spec-bible-36', 'Celestial', 'Celestial realms', 'Immortal', 'Cosmic physiology.', 'Cosmic energy manipulation, dimensional travel, immense durability, and reality-scale abilities.', 'Cosmic laws and higher-order entities.', 'Cosmic balance, creation, and observation.', 'Cosmic communication', 'Extremely rare', 'CANON', 'Cosmic Entity', 'Active', 'Cosmic hierarchy', 'Transcendent', 'Celestials are immense cosmic beings associated with creation, observation, judgment, or cosmic balance.', 'Cosmic creation.'),
('spec-bible-37', 'Astral', 'Astral plane', 'Variable', 'Non-corporeal consciousness-based physiology.', 'Astral projection, telepathy, possession, dream manipulation, and psychic techniques.', 'Mental defenses, spiritual barriers, and dimensional anchors.', 'Knowledge, consciousness, and identity.', 'Telepathic', 'Unknown', 'CANON', 'Spiritual / Dimensional', 'Active', 'Psychic communities', 'Psychic / dimensional', 'Astral beings inhabit dimensions where consciousness and thought can function as physical forces.', 'Astral plane.'),
('spec-bible-38', 'Cosmic Being', 'Cosmic space', 'Millions to infinite years', 'Cosmic lifeform.', 'Space travel, cosmic energy, extreme durability, and reality manipulation.', 'Higher cosmic laws and entities.', 'Variable.', 'Cosmic / telepathic', 'Unknown', 'CANON', 'Cosmic Lifeform', 'Active', 'Cosmic civilizations', 'Cosmic', 'Cosmic Beings operate on interstellar or universal scales.', 'Universal.'),
('spec-bible-39', 'Interdimensional', 'Variable dimensions', 'Variable', 'Reality-dependent physiology.', 'Dimensional travel, phase shifting, portal creation, and reality navigation.', 'Dimensional anchors and unstable portals.', 'Variable.', 'Variable', 'Unknown', 'CANON', 'Dimensional Entity', 'Active', 'Variable', 'Dimensional', 'Interdimensional beings originate from or naturally interact with multiple dimensions.', 'Alternate dimensions.'),
('spec-bible-40', 'Multiversal', 'Multiple realities', 'Potentially infinite', 'Beyond conventional biology.', 'Cross-universe awareness, dimensional travel, and reality interaction.', 'Higher-order cosmic laws.', 'Unknown.', 'Multiversal / telepathic', 'Unknown', 'CANON', 'Multiversal Entity', 'Active', 'Unknown', 'Transcendent', 'Multiversal beings possess awareness, existence, or influence across multiple universes.', 'Unknown.'),
('spec-bible-41', 'Primordial', 'Before conventional civilization', 'Potentially billions of years', 'Fundamentally ancient cosmic physiology.', 'Reality-scale energy manipulation and ancient cosmic knowledge.', 'Fundamental laws of existence.', 'Unknown.', 'Ancient / conceptual', 'Unknown', 'CANON', 'Ancient Cosmic Entity', 'Active', 'Ancient hierarchy', 'Beyond conventional', 'Primordials existed before or during the earliest stages of cosmic development.', 'Early universe.'),
('spec-bible-42', 'Godlike', 'Variable', 'Immortal', 'Transcendent physiology.', 'Extreme strength, durability, energy manipulation, dimensional abilities, and divine techniques.', 'Individual-specific limits and cosmic laws.', 'Individual.', 'Divine / cosmic', 'Extremely rare', 'CANON', 'Transcendent Being', 'Active', 'Divine hierarchy / independent', 'Transcendent', 'Godlike describes power approaching divine levels, not automatic omnipotence.', 'Ascension, cosmic birth, divine creation, or extreme evolution.'),
('spec-bible-43', 'Construct', 'Artificial / creator-dependent', 'Potentially indefinite', 'Artificial.', 'Construction-dependent abilities, upgrades, enchantments, and combat training.', 'Creator limitations, power source, and structural damage.', 'Usually creator-derived.', 'Programmed / learned', 'Variable', 'CANON', 'Artificial Entity', 'Active', 'Creator-dependent', 'Variable', 'Constructs are artificial beings created through technology, magic, or both.', 'Artificial creation.'),
('spec-bible-44', 'Technomorph', 'Variable', 'Potentially indefinite', 'Technological-organic physiology.', 'Technology manipulation, machine integration, self-modification, hacking, and weaponization.', 'EMP effects, incompatible systems, and technological dependency.', 'Evolution, information, and adaptation.', 'Digital / technological', 'Unknown', 'CANON', 'Technological Lifeform', 'Active', 'Networked', 'Extremely advanced', 'Technomorphs are living beings capable of manipulating, transforming, or merging with technology.', 'Evolutionary technology or artificial creation.'),
('spec-bible-45', 'Parasite', 'Variable', 'Variable', 'Host-dependent organism.', 'Host manipulation, biological adaptation, and ability acquisition through hosts.', 'Host death, immune response, and environmental vulnerability.', 'Survival.', 'Biological / telepathic', 'Variable', 'CANON', 'Symbiotic / Predatory Organism', 'Active', 'None / colonies', 'Biological', 'Parasites survive through hosts and may range from destructive organisms to complex biological partners.', 'Evolutionary or extraterrestrial.'),
('spec-bible-46', 'Hive Mind', 'Variable', 'Variable', 'Biological, artificial, or hybrid collective intelligence.', 'Collective communication, synchronized action, shared knowledge, and tactical coordination.', 'Central nodes, communication disruption, and collective vulnerability.', 'Collective survival and unity.', 'Collective communication', 'Potentially millions', 'CANON', 'Collective Intelligence', 'Active', 'Central consciousness / hierarchy', 'Variable', 'Hive Minds replace individual isolation with collective consciousness across multiple bodies.', 'Biological evolution or artificial networking.'),
('spec-bible-47', 'Unknown', 'Unknown', 'Unknown', 'Unknown.', 'Unknown.', 'Unknown.', 'Unknown.', 'Unknown', 'Unknown', 'CANON', 'Unclassified', 'Unknown', 'Unknown', 'Unknown', 'Unknown represents a deliberate gap in the universe knowledge when a species is not identified.', 'Unknown.'),
('spec-bible-48', 'Other', 'Variable', 'Variable', 'Variable.', 'Species-specific.', 'Species-specific.', 'Species-specific.', 'Variable', 'Variable', 'CANON', 'Unclassified / Unique', 'Active / Variable', 'Variable', 'Variable', 'Other is an expansion slot for species that do not fit an existing classification.', 'Species-specific.')
on conflict (id) do update set
  home_planet = coalesce(nullif(public.species.home_planet, ''), excluded.home_planet),
  lifespan = coalesce(nullif(public.species.lifespan, ''), excluded.lifespan),
  biology = coalesce(nullif(public.species.biology, ''), excluded.biology),
  abilities = coalesce(nullif(public.species.abilities, ''), excluded.abilities),
  weaknesses = coalesce(nullif(public.species.weaknesses, ''), excluded.weaknesses),
  culture = coalesce(nullif(public.species.culture, ''), excluded.culture),
  language = coalesce(nullif(public.species.language, ''), excluded.language),
  population = coalesce(nullif(public.species.population, ''), excluded.population),
  category = coalesce(nullif(public.species.category, ''), excluded.category),
  status = coalesce(nullif(public.species.status, ''), excluded.status),
  government = coalesce(nullif(public.species.government, ''), excluded.government),
  technology_level = coalesce(nullif(public.species.technology_level, ''), excluded.technology_level),
  overview = coalesce(nullif(public.species.overview, ''), excluded.overview),
  origins = coalesce(nullif(public.species.origins, ''), excluded.origins);

commit;

select count(*) as species_rows from public.species;
