-- Infernal Comics Black Knight character seed.
-- Safe to paste into Supabase SQL Editor.
-- Additive only: no deletes, truncates, drops, image writes, or overwrites.

begin;

insert into public.characters (
  id, name, code_name, aliases, species, gender, birth_date, birthplace,
  current_location, occupation, height, build, hair, eyes,
  distinguishing_features, costume, origin, description, affiliation,
  position_role, romantic_interests, enemies_rivals, primary_energy_source,
  major_abilities, secondary_abilities, signature_techniques, positive_traits,
  negative_traits, quirks_habits, physical_appearance, central_themes,
  core_philosophy, signature_quote, notable_engagements, battle_philosophy,
  character_arc, heroic_villainous_legacy, current_status, canon_status
)
values
(
  'char-bible-amara-okafor',
  'Amara Chidinma Okafor',
  '',
  '{}',
  'Human',
  'Female',
  '1999-03-14',
  'Lagos, Nigeria',
  'Victoria Island, Lagos',
  'Senior Robotics Engineer - Denver Innovations',
  '5''7"',
  'Athletic-slim',
  'Black',
  'Dark brown',
  'Small scar through left eyebrow',
  'Practical engineering clothing; later specialized field equipment.',
  'Amara grew up fascinated by machines and robotics. She joined Denver Innovations and became one of the few people Derrick trusts with his most sensitive projects.',
  'Amara is the closest thing Derrick has to a normal human connection. She knows Derrick is hiding something but does not initially know he is Black Knight.',
  'Denver Innovations',
  'Senior Robotics Engineer',
  'None established',
  'NULL; hostile Denver Innovations competitors',
  'None',
  'Robotics; mechanical engineering; programming; rapid prototyping; systems analysis',
  'Hand-to-hand combat; drone operation; emergency medicine; driving',
  'Rapid Patch - improvises temporary repairs to damaged technology.',
  'Loyal; intelligent; direct; courageous',
  'Stubborn; overprotective; cannot stop investigating',
  'Drinks ridiculous amounts of coffee while working.',
  'Young Nigerian woman with natural black hair, usually tied back while working.',
  'Trust, loyalty, technology, and human connection.',
  'A machine can be perfect. People do not have to be.',
  'Derrick, you are not the only person in this building who knows how to build something.',
  'First major Denver Innovations breach.',
  'Avoid confrontation; solve the technical problem.',
  'Amara gradually discovers Derrick''s secret and becomes one of Black Knight''s most important support figures.',
  'Potential core supporting character throughout the Black Knight series.',
  'Active',
  'CANON'
),
(
  'char-bible-tayo-adeyemi',
  'Tayo Adeyemi',
  'Detective Adeyemi',
  '{}',
  'Human',
  'Male',
  '1992-11-22',
  'Lagos, Nigeria',
  'Lagos',
  'Lagos State Police detective',
  '6''0"',
  'Broad / athletic',
  'Black',
  'Brown',
  'Wristwatch inherited from his father',
  'Plainclothes detective attire.',
  'Adeyemi has spent years investigating organized crime and technology-related crimes across Lagos. Black Knight repeatedly interferes with his investigations.',
  'He believes no individual should operate above the law. He is honest, not secretly evil, and genuinely believes Black Knight creates as many problems as he solves.',
  'Lagos State Police',
  'Detective / recurring antagonist to Black Knight',
  'None established',
  'Black Knight; organized crime groups',
  'None',
  'Investigation; interrogation; crime-scene analysis; firearms training; tactical planning',
  'Driving; hand-to-hand combat; networking',
  'Pattern Map - connects seemingly unrelated crimes.',
  'Honest; persistent; protective; intelligent',
  'Distrustful; stubborn; refuses help on principle',
  'Keeps physical notebooks despite access to police databases.',
  'Tall Nigerian man with a muscular build and closely cropped hair.',
  'Law versus justice.',
  'Good intentions do not make you accountable.',
  'If you are going to protect Lagos, start by answering to Lagos.',
  'Black Knight investigations across Lagos.',
  'Contain first, understand second.',
  'Eventually realizes Black Knight is not simply another vigilante, without necessarily accepting Derrick''s methods.',
  'Recurring lawful antagonist and possible uneasy ally.',
  'Active',
  'CANON'
),
(
  'char-bible-victor-kane',
  'Victor Emmanuel Kane',
  '',
  '{}',
  'Human',
  'Male',
  '1978-01-08',
  'Lagos, Nigeria',
  'Ikoyi, Lagos',
  'Corporate executive / investor',
  '6''1"',
  'Lean',
  'Black',
  'Dark brown',
  'Always impeccably dressed; distinctive silver cufflinks.',
  'Luxury business attire.',
  'Victor helped finance Denver Innovations during its early expansion and holds significant influence within the company.',
  'Victor believes Derrick is wasting Denver Innovations'' potential by refusing to fully militarize its technology. He should initially appear suspicious while potentially being innocent.',
  'Denver Innovations',
  'Board member / investor',
  'Unknown',
  'Derrick Denvers; corporate competitors',
  'None',
  'Corporate strategy; negotiation; finance; political networking',
  'Information gathering; manipulation',
  'Pressure Point - uses corporate leverage rather than physical force.',
  'Intelligent; ambitious; charismatic',
  'Ruthless; opportunistic; controlling',
  'Never raises his voice during arguments.',
  'Lean Nigerian man with an impeccably controlled corporate appearance.',
  'Power through influence.',
  'Technology is only valuable when someone is willing to use it.',
  'You built the future, Derrick. I am simply asking why you are afraid to sell it.',
  'Denver Innovations financing and board pressure.',
  'Use leverage, information, and negotiation before physical force.',
  'Potential future antagonist whose true allegiance remains uncertain.',
  'Corporate power broker with ambiguous allegiance.',
  'Active',
  'CANON'
),
(
  'char-bible-elias-denvers',
  'Elias Alexander Denvers',
  '',
  '{}',
  'Human',
  'Male',
  '1964',
  'Lagos, Nigeria',
  'Deceased / unknown depending on final backstory',
  'Engineer / inventor',
  '6''0"',
  'Average',
  'Black / gray',
  'Brown',
  'Old mechanical watch',
  'Practical engineering clothing.',
  'Derrick''s father and an influential engineer who helped shape Derrick''s fascination with technology.',
  'Elias should remain a major mystery character rather than simply a dead father. His research may connect directly to the technology behind Denver Innovations.',
  'Former independent researcher',
  'Derrick''s father',
  'Derrick''s mother',
  'Unknown',
  'None',
  'Engineering; physics; robotics; scientific research',
  '{}',
  '{}',
  'Brilliant; curious; patient; protective',
  'Secretive; obsessive; sometimes prioritized research over family',
  'Maintained an old mechanical watch.',
  'Older Nigerian engineer with a practical presence and a lifetime of technical work.',
  'Legacy, invention, and responsibility.',
  'Every invention eventually belongs to the person who controls it.',
  '',
  'Research connected to the Denver Innovations mystery.',
  'Investigate before acting; protect the people affected by invention.',
  'His history gradually reveals that Derrick''s family tragedy may connect to something Elias created.',
  'Foundational mystery figure in the Denvers family legacy.',
  'Deceased / unknown',
  'CANON'
),
(
  'char-bible-nadia-denvers',
  'Nadia Elise Denvers',
  '',
  '{}',
  'Human',
  'Female',
  '2001-09-03',
  'Lagos, Nigeria',
  'Unknown',
  'Unknown / university student before the family incident',
  '5''6"',
  'Slim',
  'Dark brown',
  'Brown',
  'Small crescent-shaped birthmark on right wrist',
  'Civilian clothing; often carried a small camera.',
  'Derrick''s younger sister and one of the emotional anchors of his history.',
  'Her fate should not be fully revealed in Issue #1. She may have died, disappeared, survived, or become connected to the larger conspiracy.',
  'Denvers family',
  'Derrick''s younger sister',
  'None established',
  'Unknown',
  'None',
  'Strong technical aptitude; photography; research',
  'Persuasive; highly observant',
  '{}',
  'Curious; compassionate; fearless',
  'Reckless; persistent; ignored warnings',
  'Always carried a small camera.',
  'Young Nigerian woman with a crescent-shaped birthmark on her right wrist.',
  'Family, memory, loss, and truth.',
  'If something does not make sense, there is something you are not being told.',
  'You do not have to protect everyone by yourself, Derrick.',
  'The Denvers family incident.',
  'Observe, document, and keep searching for the truth.',
  'Her story becomes increasingly important as Derrick discovers the truth behind the family incident.',
  'Emotional anchor and unresolved mystery in the Black Knight series.',
  'Unknown',
  'CANON'
)
on conflict (id) do nothing;

-- Add only relationships directly supported by the supplied character bible.
with relationship_seed(id, source, source_name, target_name, type, description) as (
  values
  ('rel-bible-amara-derrick', 'char-bible-amara-okafor', 'Amara Chidinma Okafor', 'Derrick Denvers', 'TRUSTS', 'Amara is one of the few people Derrick trusts with sensitive Denver Innovations projects.'),
  ('rel-bible-amara-null', 'char-bible-amara-okafor', 'Amara Chidinma Okafor', 'NULL', 'ENEMY_OF', 'NULL is listed among Amara''s enemies and threatens Denver Innovations.'),
  ('rel-bible-tayo-derrick', 'char-bible-tayo-adeyemi', 'Tayo Adeyemi', 'Derrick Denvers', 'INVESTIGATES', 'Adeyemi investigates Black Knight''s activities and believes no individual should operate above the law.'),
  ('rel-bible-victor-derrick', 'char-bible-victor-kane', 'Victor Emmanuel Kane', 'Derrick Denvers', 'PRESSURES', 'Victor applies board and corporate pressure because he believes Derrick is wasting Denver Innovations'' potential.'),
  ('rel-bible-elias-derrick', 'char-bible-elias-denvers', 'Elias Alexander Denvers', 'Derrick Denvers', 'PARENT_OF', 'Elias is Derrick''s father and the source of a major technology legacy mystery.'),
  ('rel-bible-nadia-derrick', 'char-bible-nadia-denvers', 'Nadia Elise Denvers', 'Derrick Denvers', 'SIBLING_OF', 'Nadia is Derrick''s younger sister and an unresolved emotional anchor of his history.')
)
insert into public.relationships (
  id, source, source_name, target, target_name, type, description, canon_status
)
select
  relationship_seed.id,
  relationship_seed.source,
  relationship_seed.source_name,
  target.id,
  relationship_seed.target_name,
  relationship_seed.type,
  relationship_seed.description,
  'CANON'
from relationship_seed
join public.characters target
  on lower(trim(target.name)) = lower(trim(relationship_seed.target_name))
on conflict (id) do nothing;

commit;

select count(*) as seeded_characters
from public.characters
where id in ('char-bible-amara-okafor', 'char-bible-tayo-adeyemi', 'char-bible-victor-kane', 'char-bible-elias-denvers', 'char-bible-nadia-denvers');
