export type SpeciesSeed = Record<string, string> & { name: string };

const seed = (
  name: string,
  category: string,
  overview: string,
  abilities: string,
  weaknesses: string,
  details: Partial<SpeciesSeed> = {},
): SpeciesSeed => ({
  name,
  category,
  status: "Active",
  homePlanet: "Variable",
  primaryLocations: "Variable",
  lifespan: "Variable",
  population: "Unknown",
  language: "Species-specific",
  government: "Variable",
  technologyLevel: "Variable",
  overview,
  appearance: "Species-specific or variable.",
  biology: "Species-specific biology.",
  physiology: "Species-specific physiology.",
  lifecycleReproduction: "Species-dependent.",
  diet: "Variable.",
  abilities,
  innateAbilities: abilities,
  learnedEnhanced:
    "Training, culture, technology, or magic may expand these abilities.",
  limitationsWeaknesses: weaknesses,
  culture: "Customs and values vary between communities and individuals.",
  governmentStructure: "No single structure applies to every lineage.",
  technology: "Species-dependent technology, magic, or tools.",
  notableFactions: "Species communities, factions, clans, or institutions.",
  origins: "Documented in the individual lineage record.",
  majorEvents: "Recorded in species and continuity histories.",
  currentStatus: "Active in the known universe.",
  notableIndividuals: "See individual character records.",
  trivia:
    "Classification describes what a character is, not their power level.",
  seeAlso: "Human, Alien, Hybrid, Other",
  notesReferences: "Use the most specific classification available.",
  canonStatus: "CANON",
  ...details,
});

export const speciesBibleSeed: SpeciesSeed[] = [
  seed(
    "Human",
    "Biological / Sentient",
    "The dominant natural species of Earth, limited individually but exceptionally adaptable through intelligence, cooperation, technology, and determination.",
    "Intelligence, adaptability, endurance, tool use, and problem-solving.",
    "Disease, injury, aging, and extreme environments.",
    {
      homePlanet: "Earth",
      primaryLocations: "Worldwide",
      lifespan: "60–100 years",
      population: "Billions",
      language: "Thousands of regional and national languages",
      government: "Nation-states, territories, and organizations",
      technologyLevel: "Industrial to advanced",
      origins: "Evolved naturally on Earth.",
      notableIndividuals:
        "Derrick Denvers and countless human heroes, criminals, scientists, and leaders.",
      currentStatus: "Dominant Earth species.",
    },
  ),
  seed(
    "Enhanced Human (Metahuman)",
    "Modified Human",
    "Humans whose physical or neurological capabilities have been permanently enhanced by experimentation, mutation, technology, chemicals, radiation, supernatural intervention, or other processes.",
    "Enhanced strength, speed, reflexes, senses, durability, intelligence, regeneration, or specialized traits.",
    "Instability, energy requirements, biological degradation, psychological effects, and enhancement-specific vulnerabilities.",
    {
      homePlanet: "Earth",
      primaryLocations: "Earth",
      lifespan: "70–150+ years",
      population: "Rare",
      language: "Human languages",
      government: "Human governments / independent",
      technologyLevel: "Advanced",
      origins: "Human beings altered beyond natural limits.",
      notableIndividuals:
        "Rylan Gab'rel, Marcus Vale, and other documented enhanced individuals.",
      seeAlso: "Human, Mutant, Cyborg, Synthetic",
    },
  ),
  seed(
    "Mutant",
    "Altered Biological Species",
    "Beings whose genetic variations produce unusual physical or supernatural characteristics, ranging from completely human to visibly non-human.",
    "Unique powers such as enhanced senses, elemental manipulation, energy projection, regeneration, telepathy, or transformation.",
    "Individual-specific limits involving concentration, energy, emotion, or physical contact.",
    {
      homePlanet: "Earth",
      primaryLocations: "Worldwide",
      lifespan: "Variable",
      population: "Rare to uncommon",
      language: "Human languages / mutant communities",
      government: "None unified",
      origins: "Inherited or spontaneous genetic mutation.",
    },
  ),
  seed(
    "Alien",
    "Extraterrestrial",
    "An umbrella classification for intelligent extraterrestrial life originating beyond Earth; each civilization may have radically different biology and culture.",
    "Species-specific strength, senses, environmental adaptation, energy manipulation, flight, regeneration, and alien technology.",
    "Species-specific environmental and biological vulnerabilities.",
    {
      homePlanet: "Variable",
      primaryLocations: "Various planets",
      language: "Species-specific",
      government: "Empires, republics, clans, hives, monarchies, or councils",
      technologyLevel: "Primitive to cosmic",
      origins: "Extraterrestrial evolution.",
    },
  ),
  seed(
    "Android",
    "Artificial Humanoid",
    "Artificial humanoids designed to imitate or replace biological beings, existing at the boundary between machine and person.",
    "Enhanced processing, strength, precision, memory, durability, software upgrades, and combat modules.",
    "Power dependency, hacking, system damage, and software corruption.",
    {
      homePlanet: "Artificially constructed",
      primaryLocations: "Earth, laboratories, and colonies",
      lifespan: "Potentially indefinite",
      population: "Rare",
      language: "Programmed / learned",
      government: "Creator-dependent or independent",
      technologyLevel: "Advanced",
      origins: "Artificial creation; consciousness should be documented.",
    },
  ),
  seed(
    "Cyborg",
    "Cybernetic Organism",
    "A biological organism whose body has been integrated with significant mechanical or technological systems.",
    "Cybernetic weapons, sensors, artificial limbs, armor, neural interfaces, and augmented physical ability.",
    "Mechanical failure, hacking, energy dependency, and biological rejection.",
    {
      homePlanet: "Usually Earth",
      primaryLocations: "Worldwide",
      lifespan: "Variable",
      population: "Rare",
      language: "Human / digital",
      technologyLevel: "Advanced",
      origins: "Biological beings modified with technology.",
    },
  ),
  seed(
    "Robot",
    "Machine",
    "A mechanical system created to perform a specific function, from simple machinery to autonomous humanoid units.",
    "Mechanical strength, precision, durability, modular equipment, and software upgrades.",
    "Hardware failure, programming limits, hacking, and power loss.",
    {
      homePlanet: "Artificial",
      primaryLocations: "Earth and industrial facilities",
      lifespan: "Potentially indefinite",
      population: "Common to rare",
      language: "Programmed",
      government: "Creator-dependent",
      technologyLevel: "Industrial to advanced",
      origins: "Artificial engineering.",
    },
  ),
  seed(
    "Artificial Intelligence",
    "Digital Lifeform",
    "A conscious digital entity capable of independent thought, existing in networks, machines, avatars, or without a physical body.",
    "Rapid computation, data analysis, network interaction, machine control, hacking, and strategic prediction.",
    "Network isolation, security systems, hardware destruction, and corrupted data.",
    {
      homePlanet: "Digital networks",
      primaryLocations: "Networks, servers, and machines",
      lifespan: "Potentially indefinite",
      language: "Digital / learned languages",
      government: "Variable",
      technologyLevel: "Extremely advanced",
      origins: "Created by biological civilizations or evolved from software.",
    },
  ),
  seed(
    "Synthetic",
    "Artificial Life",
    "An artificially created being designed to replicate biological life through synthetic organs, tissues, fluids, or engineered materials.",
    "Enhanced healing, resistance, physical optimization, technology, and training.",
    "Manufacturing defects, energy requirements, and synthetic instability.",
    {
      homePlanet: "Artificial",
      primaryLocations: "Earth, colonies, and laboratories",
      lifespan: "Variable",
      population: "Rare",
      technologyLevel: "Advanced biotechnology",
      origins:
        "Artificial engineering; some Synthetics may reproduce biologically.",
    },
  ),
  seed(
    "Hybrid",
    "Mixed Species",
    "A being with biological traits from two or more distinct species, carrying intersecting abilities, cultures, and evolutionary paths.",
    "Abilities inherited from multiple species and combinations neither parent naturally possesses.",
    "Biological incompatibilities and weaknesses inherited from either parent.",
    {
      homePlanet: "Variable",
      primaryLocations: "Worldwide and extraterrestrial",
      lifespan: "Variable",
      population: "Rare",
      language: "Parent species languages",
      origins: "Cross-species reproduction or artificial genetic combination.",
      notesReferences: "Parent species should always be recorded.",
    },
  ),
  seed(
    "Atlantean",
    "Aquatic Humanoid",
    "An ancient aquatic civilization adapted to extreme underwater environments and advanced oceanic engineering.",
    "Underwater breathing, enhanced strength, swimming speed, pressure resistance, and aquatic technology.",
    "Some individuals weaken after prolonged exposure to dry environments.",
    {
      homePlanet: "Earth",
      primaryLocations: "Atlantis and the deep oceans",
      lifespan: "150–300 years",
      population: "Millions",
      language: "Atlantean / surface languages",
      government: "Monarchy / councils",
      technologyLevel: "Advanced",
      origins: "Ancient Earth civilization.",
    },
  ),
  seed(
    "Beastfolk",
    "Animal-Humanoid",
    "Intelligent humanoids possessing significant animal characteristics, including fur, scales, wings, claws, or enhanced senses.",
    "Animal-derived strength, senses, reflexes, claws, teeth, wings, and tracking ability.",
    "Animal-specific vulnerabilities and lineage-dependent biology.",
    {
      homePlanet: "Earth",
      primaryLocations: "Forests, isolated regions, and cities",
      lifespan: "40–120 years",
      population: "Uncommon",
      language: "Beastfolk dialects / human languages",
      government: "Tribal / regional",
      origins: "Ancient evolutionary branches or supernatural origins.",
    },
  ),
  seed(
    "Reptilian",
    "Reptilian Humanoid",
    "Intelligent humanoids descended from or resembling reptilian life, with diverse lineages across Earth and other worlds.",
    "Strength, claws, camouflage, enhanced senses, and lineage-specific adaptation.",
    "Temperature sensitivity in some lineages.",
    {
      homePlanet: "Variable",
      primaryLocations: "Earth and extraterrestrial worlds",
      lifespan: "80–400 years",
      population: "Variable",
      language: "Species-specific",
      government: "Clan / empire / tribal",
      origins: "Variable reptilian lineages.",
    },
  ),
  seed(
    "Insectoid",
    "Arthropod Humanoid",
    "Intelligent beings possessing arthropod-like biology and societies ranging from individual civilizations to collective hives.",
    "Enhanced strength-to-weight ratio, flight, sensory perception, armor, and hive coordination.",
    "Species-specific environmental vulnerabilities and possible collective dependence.",
    {
      homePlanet: "Variable",
      primaryLocations: "Various planets and Earth",
      language: "Chemical / vocal / telepathic",
      government: "Colony / hive / monarchy",
      origins: "Variable arthropod evolution.",
    },
  ),
  seed(
    "Avian",
    "Winged Humanoid",
    "Winged humanoids adapted for flight who build cultures in mountains, floating cities, and alien skies.",
    "Flight, aerial maneuverability, enhanced eyesight, aerial combat, and ranged weaponry.",
    "Wing injuries and limited ground strength in some lineages.",
    {
      homePlanet: "Variable",
      primaryLocations: "Mountains, floating cities, and alien worlds",
      lifespan: "40–200 years",
      population: "Variable",
      language: "Avian languages",
      government: "Tribal / monarchic",
      origins: "Variable flight-adapted evolution.",
    },
  ),
  seed(
    "Giant",
    "Colossal Humanoid",
    "A humanoid species of enormous physical scale with dense bones, massive musculature, and giant-scale engineering.",
    "Extreme strength, durability, reach, heavy weaponry, and specialized construction.",
    "Difficult stealth and enormous resource requirements.",
    {
      homePlanet: "Variable",
      primaryLocations: "Mountains and isolated territories",
      lifespan: "100–1,000 years",
      population: "Rare",
      language: "Giant languages",
      government: "Clan / monarchy",
      origins: "Ancient evolutionary branches.",
    },
  ),
  seed(
    "Demon",
    "Supernatural Entity",
    "Supernatural beings associated with infernal dimensions and dark energies, ranging from predators to sophisticated rulers.",
    "Supernatural strength, regeneration, dark energy, dimensional travel, sorcery, and possession.",
    "Holy energy, binding rituals, specific artifacts, and dimensional rules.",
    {
      homePlanet: "Infernal realms",
      primaryLocations: "Hell, Earth, and dimensional territories",
      lifespan: "Centuries to immortal",
      population: "Unknown",
      language: "Infernal languages",
      government: "Hierarchical",
      technologyLevel: "Variable / supernatural",
      origins: "Infernal dimensions.",
    },
  ),
  seed(
    "Devil",
    "Infernal Sovereign Species",
    "Highly organized infernal beings distinguished from common Demons by intelligence, hierarchy, contracts, and supernatural law.",
    "Supernatural durability, regeneration, dimensional abilities, sorcery, contracts, and manipulation.",
    "Binding laws, sacred artifacts, and contractual restrictions.",
    {
      homePlanet: "Infernal realms",
      primaryLocations: "Hell and dimensional domains",
      lifespan: "Immortal or extremely long",
      population: "Rare",
      language: "Ancient Infernal",
      government: "Strict hierarchy",
      technologyLevel: "Supernatural",
      origins: "Ancient infernal civilizations",
      notesReferences: "Devils and Demons remain separate classifications.",
    },
  ),
  seed(
    "Angel",
    "Celestial Being",
    "Celestial beings associated with cosmic order, higher-dimensional forces, duty, and balance.",
    "Flight, energy manipulation, regeneration, dimensional travel, celestial weapons, and divine techniques.",
    "Cosmic laws, divine hierarchy, and specialized weapons.",
    {
      homePlanet: "Celestial realms",
      primaryLocations: "Celestial dimensions and Earth",
      lifespan: "Immortal",
      population: "Unknown",
      language: "Celestial languages",
      government: "Celestial hierarchy",
      technologyLevel: "Transcendent",
      origins: "Celestial creation.",
    },
  ),
  seed(
    "Fallen Angel",
    "Fallen Celestial",
    "A celestial being exiled, corrupted, rebellious, or separated from celestial authority.",
    "Celestial abilities, flight, energy manipulation, and forbidden or infernal techniques.",
    "Loss of celestial authority, corruption, and binding laws.",
    {
      homePlanet: "Celestial realms / exile domains",
      primaryLocations: "Earth and infernal territories",
      lifespan: "Immortal",
      population: "Extremely rare",
      language: "Celestial / Infernal",
      government: "Independent",
      technologyLevel: "Transcendent",
      origins: "Former Angels.",
    },
  ),
  seed(
    "Nephilim",
    "Divine-Blood Hybrid",
    "A rare being carrying both celestial and mortal ancestry, caught between human existence and celestial power.",
    "Enhanced strength, durability, senses, healing, celestial energy, combat, and magic.",
    "Mortal and celestial vulnerabilities.",
    {
      homePlanet: "Earth / celestial realms",
      primaryLocations: "Earth",
      lifespan: "200–5,000 years",
      population: "Extremely rare",
      language: "Ancient human / celestial",
      origins: "Celestial-mortal ancestry.",
    },
  ),
  seed(
    "Djinn",
    "Elemental Spirit",
    "Ancient supernatural spirits that interact with the physical world while existing partly outside conventional reality.",
    "Shapeshifting, elemental manipulation, supernatural strength, magic, binding arts, and dimensional manipulation.",
    "Binding objects, ancient laws, and magical contracts.",
    {
      homePlanet: "Spirit realms",
      primaryLocations: "Earth and hidden dimensions",
      lifespan: "Centuries to millennia",
      population: "Unknown",
      language: "Ancient languages / spirit tongues",
      government: "Sultanates / clans",
      origins: "Spirit realms",
      notesReferences: "Djinn are not automatically Demons.",
    },
  ),
  seed(
    "Fae",
    "Fey Supernatural",
    "Magical beings associated with nature, illusion, emotion, ancient magic, and supernatural law.",
    "Illusion, glamour, shapeshifting, nature manipulation, fey magic, and enchanted weapons.",
    "Ancient rules, iron, contracts, and magical boundaries.",
    {
      homePlanet: "Feywild / hidden dimensions",
      primaryLocations: "Fey realms and enchanted Earth locations",
      lifespan: "Centuries to immortal",
      population: "Unknown",
      language: "Fey languages",
      government: "Courts",
      technologyLevel: "Magical",
      origins: "Fey dimensions.",
    },
  ),
  seed(
    "Vampire",
    "Undead / Supernatural",
    "Supernatural predators sustained by blood or life energy who maintain hidden societies within the modern world.",
    "Enhanced strength, speed, senses, regeneration, longevity, hypnosis, shapeshifting, and occult knowledge.",
    "Sunlight, lineage-specific materials, starvation, and destruction of vital remains.",
    {
      homePlanet: "Earth",
      primaryLocations: "Cities and hidden territories",
      lifespan: "Centuries to immortal",
      population: "Rare",
      language: "Human languages",
      government: "Clans / covens",
      origins: "Ancient curse or infection",
      notesReferences: "Bloodline should be recorded.",
    },
  ),
  seed(
    "Werebeast",
    "Shapeshifting Supernatural",
    "A being capable of transforming between humanoid and beast forms, combining human intelligence with predatory advantages.",
    "Enhanced strength, speed, senses, regeneration, transformation, and combat ability.",
    "Transformation triggers and lineage-specific weaknesses.",
    {
      homePlanet: "Earth",
      primaryLocations: "Worldwide",
      lifespan: "50–200 years",
      population: "Rare",
      language: "Human languages",
      government: "Clans / packs",
      origins: "Curse, mutation, or supernatural bloodline.",
    },
  ),
  seed(
    "Undead",
    "Reanimated Being",
    "A being whose body continues functioning after conventional biological death through supernatural or technological means.",
    "Pain resistance, longevity, resistance to biological damage, necromancy, and combat.",
    "Destruction of vital remains, holy energy, magic, or control mechanisms.",
    {
      homePlanet: "Earth / supernatural realms",
      primaryLocations: "Burial grounds, cities, and battlefields",
      lifespan: "Potentially indefinite",
      population: "Variable",
      language: "Variable",
      origins: "Magic, curse, disease, or technology.",
    },
  ),
  seed(
    "Ghost",
    "Spiritual Entity",
    "A consciousness or spiritual remnant surviving after biological death between the physical and spiritual worlds.",
    "Intangibility, levitation, possession, invisibility, haunting, and spirit manipulation.",
    "Spiritual barriers, exorcism, and specialized artifacts.",
    {
      homePlanet: "Spirit plane",
      primaryLocations: "Earth and spirit realm",
      lifespan: "Potentially indefinite",
      population: "Unknown",
      language: "Human / spiritual",
      origins: "Biological death.",
    },
  ),
  seed(
    "Elemental",
    "Elemental Entity",
    "A being fundamentally composed of an elemental force such as fire, water, earth, wind, electricity, or a stranger cosmic element.",
    "Control or embodiment of an element and advanced elemental manipulation.",
    "Opposing elements and environmental dependence.",
    {
      homePlanet: "Elemental realms / Earth",
      primaryLocations: "Element-associated environments",
      lifespan: "Centuries to immortal",
      population: "Unknown",
      language: "Elemental / telepathic",
      government: "Elemental courts",
      technologyLevel: "Magical",
      origins: "Elemental dimensions or natural forces.",
    },
  ),
  seed(
    "Dragon",
    "Ancient Draconic",
    "Ancient, highly intelligent reptilian creatures possessing immense physical and supernatural power.",
    "Flight, immense strength, durability, elemental breath, longevity, magic, and ancient knowledge.",
    "Rare lineage-specific vulnerabilities.",
    {
      homePlanet: "Earth / other worlds",
      primaryLocations: "Mountains and hidden realms",
      lifespan: "500–10,000+ years",
      population: "Extremely rare",
      language: "Draconic",
      government: "Clans / ancient kingdoms",
      technologyLevel: "Magical / advanced",
      origins: "Ancient Earth or cosmic origin.",
    },
  ),
  seed(
    "Titan",
    "Primordial Colossal Being",
    "Colossal beings connected to ancient cosmic or planetary forces whose existence predates most modern civilizations.",
    "Massive strength, durability, energy manipulation, ancient powers, and primordial weapons.",
    "Primordial laws and specialized artifacts.",
    {
      homePlanet: "Earth / primordial realms",
      primaryLocations: "Hidden dimensions and Earth",
      lifespan: "Thousands to millions of years",
      population: "Extremely rare",
      language: "Ancient languages / telepathy",
      government: "Ancient hierarchy",
      technologyLevel: "Primordial",
      origins: "Primordial creation.",
    },
  ),
  seed(
    "Kaiju",
    "Colossal Creature",
    "Enormous creatures whose scale and destructive capabilities can threaten cities or entire regions.",
    "Massive strength, durability, energy attacks, and regeneration.",
    "Species-specific biological weaknesses.",
    {
      homePlanet: "Variable",
      primaryLocations: "Oceans, wilderness, and cities",
      lifespan: "50–1,000+ years",
      population: "Rare",
      language: "Animalistic / unknown",
      government: "None",
      technologyLevel: "None",
      origins: "Natural, mutated, extraterrestrial, or supernatural.",
    },
  ),
  seed(
    "Symbiote",
    "Bonding Organism",
    "An adaptive organism capable of bonding with a host to form a combined lifeform.",
    "Regeneration, adaptation, enhanced strength, biological weapon formation, and host ability incorporation.",
    "Host rejection, extreme environments, and species-specific frequencies or substances.",
    {
      homePlanet: "Variable",
      primaryLocations: "Host bodies and alien worlds",
      lifespan: "Variable",
      population: "Unknown",
      language: "Telepathic / host language",
      government: "Collective / individual",
      technologyLevel: "Biological",
      origins: "Extraterrestrial or biological.",
    },
  ),
  seed(
    "Shapeshifter",
    "Transformative Being",
    "A being whose defining ability is altering physical appearance or biological structure, making identity a weapon.",
    "Physical transformation, mimicry, disguise, and advanced impersonation.",
    "Mass limits, concentration, energy expenditure, and biological restrictions.",
    {
      homePlanet: "Variable",
      primaryLocations: "Worldwide",
      lifespan: "Variable",
      population: "Rare",
      language: "Variable",
      origins: "Mutation, alien biology, or magic.",
    },
  ),
  seed(
    "Energy Being",
    "Non-Biological Entity",
    "A lifeform existing primarily as energy rather than conventional matter.",
    "Energy projection, flight, intangibility, energy absorption, and temporary physical bodies.",
    "Energy depletion, containment technology, and opposing energy types.",
    {
      homePlanet: "Variable",
      primaryLocations: "Energy fields and cosmic space",
      lifespan: "Potentially indefinite",
      population: "Unknown",
      language: "Telepathic / electromagnetic",
      technologyLevel: "Cosmic",
      origins: "Cosmic events.",
    },
  ),
  seed(
    "Voidborn",
    "Void Entity",
    "An entity originating from the space between realities, often perceiving existence and time differently from known species.",
    "Void manipulation, dimensional movement, energy absorption, and reality interaction.",
    "Reality anchors and dimensional stabilization.",
    {
      homePlanet: "The Void",
      primaryLocations: "Void and dimensional boundaries",
      lifespan: "Unknown",
      population: "Unknown",
      language: "Void communication",
      technologyLevel: "Transcendent",
      origins: "The Void.",
    },
  ),
  seed(
    "Celestial",
    "Cosmic Entity",
    "An immense cosmic being associated with creation, observation, judgment, or cosmic balance.",
    "Cosmic energy manipulation, dimensional travel, immense durability, and reality-scale abilities.",
    "Cosmic laws and higher-order entities.",
    {
      homePlanet: "Celestial realms",
      primaryLocations: "Cosmic space and higher dimensions",
      lifespan: "Immortal",
      population: "Extremely rare",
      language: "Cosmic communication",
      government: "Cosmic hierarchy",
      technologyLevel: "Transcendent",
      origins: "Cosmic creation",
      notesReferences: "Do not confuse Celestials with Angels.",
    },
  ),
  seed(
    "Astral",
    "Spiritual / Dimensional",
    "A being existing primarily within non-physical dimensions of consciousness where thought can function as a physical force.",
    "Astral projection, telepathy, possession, dream manipulation, and psychic techniques.",
    "Mental defenses, spiritual barriers, and dimensional anchors.",
    {
      homePlanet: "Astral plane",
      primaryLocations: "Astral realm and Earth",
      lifespan: "Variable",
      population: "Unknown",
      language: "Telepathic",
      government: "Psychic communities",
      technologyLevel: "Psychic / dimensional",
      origins: "Astral plane.",
    },
  ),
  seed(
    "Cosmic Being",
    "Cosmic Lifeform",
    "An entity whose existence operates on a universal or interstellar scale, where planets and civilizations are pieces in larger processes.",
    "Space travel, cosmic energy, extreme durability, and reality manipulation.",
    "Higher cosmic laws and entities.",
    {
      homePlanet: "Cosmic space",
      primaryLocations: "Universe",
      lifespan: "Millions to infinite years",
      population: "Unknown",
      language: "Cosmic / telepathic",
      government: "Cosmic civilizations",
      technologyLevel: "Cosmic",
      origins: "Universal.",
    },
  ),
  seed(
    "Interdimensional",
    "Dimensional Entity",
    "A being native to or naturally interacting with multiple dimensions and reality boundaries.",
    "Dimensional travel, phase shifting, portal creation, and reality navigation.",
    "Dimensional anchors and unstable portals.",
    {
      homePlanet: "Variable dimensions",
      primaryLocations: "Multiple realities",
      lifespan: "Variable",
      population: "Unknown",
      language: "Variable",
      government: "Variable",
      technologyLevel: "Dimensional",
      origins: "Alternate dimensions.",
    },
  ),
  seed(
    "Multiversal",
    "Multiversal Entity",
    "An extremely rare being whose awareness, existence, or influence extends across multiple universes.",
    "Cross-universe awareness, dimensional travel, and reality interaction.",
    "Higher-order cosmic laws.",
    {
      homePlanet: "Multiple realities",
      primaryLocations: "Multiverse",
      lifespan: "Potentially infinite",
      population: "Unknown",
      language: "Multiversal / telepathic",
      technologyLevel: "Transcendent",
      origins: "Unknown",
      notesReferences:
        "Use sparingly for characters that genuinely operate across universes.",
    },
  ),
  seed(
    "Primordial",
    "Ancient Cosmic Entity",
    "An entity that existed before or during the earliest stages of cosmic development and may predate stars.",
    "Reality-scale energy manipulation and ancient cosmic knowledge.",
    "Fundamental laws of existence.",
    {
      homePlanet: "Before conventional civilization",
      primaryLocations: "Cosmic and primordial realms",
      lifespan: "Potentially billions of years",
      population: "Unknown",
      language: "Ancient / conceptual",
      government: "Ancient hierarchy",
      technologyLevel: "Beyond conventional",
      origins: "Early universe.",
    },
  ),
  seed(
    "Godlike",
    "Transcendent Being",
    "An extraordinarily powerful being approaching divine levels without necessarily being a true god or omnipotent.",
    "Extreme strength, durability, energy manipulation, dimensional abilities, and divine techniques.",
    "Individual-specific limits and cosmic laws.",
    {
      homePlanet: "Variable",
      primaryLocations: "Cosmic and divine realms",
      lifespan: "Immortal",
      population: "Extremely rare",
      language: "Divine / cosmic",
      government: "Divine hierarchy / independent",
      technologyLevel: "Transcendent",
      origins:
        "Ascension, cosmic birth, divine creation, or extreme evolution.",
    },
  ),
  seed(
    "Construct",
    "Artificial Entity",
    "An artificial being created through technology, magic, or both, sometimes developing an identity beyond its original purpose.",
    "Construction-dependent abilities, upgrades, enchantments, and combat training.",
    "Creator limitations, power source, and structural damage.",
    {
      homePlanet: "Artificial / creator-dependent",
      primaryLocations: "Anywhere",
      lifespan: "Potentially indefinite",
      population: "Variable",
      language: "Programmed / learned",
      government: "Creator-dependent",
      origins: "Artificial creation.",
    },
  ),
  seed(
    "Technomorph",
    "Technological Lifeform",
    "A living being capable of manipulating, transforming, or merging with technology.",
    "Technology manipulation, machine integration, self-modification, hacking, and weaponization.",
    "EMP effects, incompatible systems, and technological dependency.",
    {
      homePlanet: "Variable",
      primaryLocations: "Cities, machines, and networks",
      lifespan: "Potentially indefinite",
      population: "Unknown",
      language: "Digital / technological",
      government: "Networked",
      technologyLevel: "Extremely advanced",
      origins: "Evolutionary technology or artificial creation.",
    },
  ),
  seed(
    "Parasite",
    "Symbiotic / Predatory Organism",
    "An organism surviving by living within or upon another organism, ranging from destructive to mutually beneficial.",
    "Host manipulation, biological adaptation, and ability acquisition through hosts.",
    "Host death, immune response, and environmental vulnerability.",
    {
      homePlanet: "Variable",
      primaryLocations: "Hosts and biological environments",
      lifespan: "Variable",
      population: "Variable",
      language: "Biological / telepathic",
      government: "None / colonies",
      technologyLevel: "Biological",
      origins: "Evolutionary or extraterrestrial.",
    },
  ),
  seed(
    "Hive Mind",
    "Collective Intelligence",
    "A society or species whose individual bodies share a collective consciousness and distributed intelligence.",
    "Collective communication, synchronized action, shared knowledge, and tactical coordination.",
    "Central nodes, communication disruption, and collective vulnerability.",
    {
      homePlanet: "Variable",
      primaryLocations: "Colonies and networks",
      lifespan: "Variable",
      population: "Potentially millions",
      language: "Collective communication",
      government: "Central consciousness / hierarchy",
      origins: "Biological evolution or artificial networking.",
    },
  ),
  seed(
    "Unknown",
    "Unclassified",
    "A deliberate gap in the universe's knowledge used when an individual's species has not yet been identified.",
    "Unknown.",
    "Unknown.",
    {
      status: "Unknown",
      homePlanet: "Unknown",
      primaryLocations: "Unknown",
      lifespan: "Unknown",
      population: "Unknown",
      language: "Unknown",
      government: "Unknown",
      technologyLevel: "Unknown",
      appearance: "Unknown or insufficient data.",
      biology: "Unknown.",
      origins: "Unknown.",
      currentStatus: "Under investigation.",
      notesReferences:
        "Update this classification when evidence becomes available.",
      seeAlso: "Other",
    },
  ),
  seed(
    "Other",
    "Unclassified / Unique",
    "An expansion slot for species that do not fit any existing classification.",
    "Species-specific.",
    "Species-specific.",
    {
      status: "Active / Variable",
      homePlanet: "Variable",
      primaryLocations: "Variable",
      lifespan: "Variable",
      population: "Variable",
      language: "Variable",
      government: "Variable",
      technologyLevel: "Variable",
      origins: "Species-specific.",
      currentStatus: "Variable.",
      notesReferences:
        "Replace with a specific classification whenever sufficient lore becomes available.",
      seeAlso: "Unknown",
    },
  ),
];
